name: Send Scheduled Notifications

on:
  schedule:
    # Runs every minute
    - cron: "2/5 * * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Send Due Notifications
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            https://fkhedzdbqlsuuahdjhgm.supabase.co/functions/v1/send-scheduled-notifications
